name: CI

on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn

    - run: yarn build

    - run: yarn lint

    - run: yarn test --reporters=jest-junit --runInBand

    - name: Codecov
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
